# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'MasonryTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'
  # Pods for MasonryTest
  
  target 'MasonryTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MasonryTestUITests' do
    # Pods for testing
  end

end
