# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ZGNewsReading' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZGNewsReading
  pod 'SnapKit', '~> 5.0.0'
  target 'ZGNewsReadingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZGNewsReadingUITests' do
    # Pods for testing
  end

end
